name: update gh-pages

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - name: Update gh-pages
        run: |
          echo $GITHUB_ACTOR
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --local user.name $GITHUB_ACTOR
          git fetch --all
          git checkout gh-pages
          git pull
          git reset --hard origin/master
          rm -rf dist
      - run: yarn build --env public-path=/Genoverse/dist/
      - name: Commit and push files
        run: |
          echo $GITHUB_ACTOR
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --local user.name $GITHUB_ACTOR
          git add -f dist
          git commit -m "Added dist folder"
          git push --force origin gh-pages
